// All words the player reads, in one place. Map, cell and item names live
// with their data; everything else is here so a translation only touches this file.

export const S = {
  rollPrompt: n => `${n}, roll the dice!`,
  rollAgain: n => `${n}, roll again!`,
  itemHint: 'Use an item first, or just roll.',
  armedDouble: 'Double dice ready — roll two!',
  armedGolden: n => `Golden die set to ${n}.`,
  armedRemote: n => `Remote die set to ${n}.`,
  skipped: n => `${n} misses this turn!`,
  trapped: n => `${n} is stuck and will miss a turn!`,
  bump: (a, b) => `${a} bumped ${b} back!`,
  blocked: n => `${n}'s shield saved them!`,
  gotItem: (n, item) => `${n} found ${item}!`,
  swap: (a, b) => `${a} swapped places with ${b}!`,
  frozen: (a, b) => `${a} froze ${b} — they miss a turn!`,
  bananaDrop: n => `${n} dropped a banana 🍌`,
  banana: 'Slipped on a banana!',
  quake: 'Earthquake! Everyone else stumbles back.',
  kraken: n => `The kraken grabs ${n}!`,
  shuffle: (a, b) => `Teleporter! ${a} and ${b} swap places.`,
  finish: n => `${n} made it!`,
  rollAgainPop: 'Roll again!',
  turnBanner: n => `${n}'s turn!`,
  skipBanner: n => `${n} is stuck…`,
  six: 'Six! Roll again!',

  setupTitle: 'Choose your adventure',
  players: 'Players',
  start: "Let's go!",
  resume: 'Continue game',
  avatarHint: 'Tap the face to change it',
  pickPlayer: item => `${item}: who's the target?`,
  pickNumber: item => `${item}: pick your number`,
  cancel: 'Cancel',
  wins: n => `${n} wins!`,
  winsMsg: 'First to the finish! Keep playing for the other places?',
  keepRacing: 'Keep playing',
  results: 'Final results',
  rematch: 'Play again',
  newGame: 'New game',
  place: ['1st', '2nd', '3rd', '4th'],
  statLine: s => `${s.ladders} ups · ${s.slides} downs · ${s.bumps} bumps · ${s.items} items`,
  confirmNew: 'Start a new game? This one will be lost.',
  help: 'How to play',
  close: 'Got it'
};
